contact_links:
  - name: GitHub Discussions
    url: https://github.com/kestra-io/kestra/discussions
    about: Ask questions about Kestra on Github
  - name: Chat
    url: https://join.slack.com/t/kestra-io/shared_invite/zt-193shv281-rK9QOEfZC2_vEbDO7Uxtbw
    about: Chat with us on Slack.