contact_links:
  - name: GitHub Discussions
    url: https://github.com/kestra-io/kestra/discussions
    about: Ask questions about Kestra on Github
  - name: Chat
    url: https://api.kestra.io/v1/communities/slack/redirect
    about: Chat with us on Slack.